### PR TITLE
dired-rsync: support non-standard ssh port

### LINKED ISSUE #18: Transfer fails if Tramp ssh path contains port number
I am using ssh tunnel to connect to a server. Tramp uses `#` to separate port number from the host name. I am guessing dired-rsync needs to replace `#port` with `-p port` which is what rsync expects.
```
ssh: Could not resolve hostname localhost#2222: Name or service not known

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
```

### PR DESCRIPTION
**Pull request by ilupin**
Hi, this patch adds support for source/dest files containing ssh port, which should fix #18

### CODE REVIEW

**Comment by stsquad** [comment]
Hi @ilupin thanks for the patch. 

Could you please extract the port extraction code into a separate function (like we have for `dired-rsync--extract-host-from-tramp)? For bonus points extend the ert tests to test the port extraction and ensure the other functions don't fail when parsing tramp paths with embedded ports.

**Comment by stsquad** [comment]
Thanks for the changes. Doing some integration testing I realised it still fails for the remote to remote case (see  dired-rsync--remote-to-remote-cmd). Would you be able to look at that?

**Comment by stsquad** [comment]
@ilupin I've also fixed the broken Travis CI by moving to GitHub actions and fixed up the currently failing ERT tests so you should pick that up when you next rebase.

**Comment by ilupin** [comment]
The remote to remote case has been supported.

**Comment by stsquad** [comment]
@ilupin thanks for those fixes and your contribution.

**Pull request merged**
